### ISSUE TITLE
Suggestion: use viewport unit instead of custom property

### ISSUE THREAD

**Issue by surgeboris** [bookiza/toucaan#13]
In [baseline CSS article](https://bubblin.io/blog/baseline-CSS) you're introducing a `--bu` custom property to use for blockscoped typography. As far as I can understand it your definition of `--bu` is completely equivalent to definition of the [`vmin` viewport unit](https://developer.mozilla.org/en-US/docs/Web/CSS/length#vmin). IMO it is much easier to use `vmin` instead of a `--bu` + `calc` combination as Toucan's base unit...

**Comment by marvindanig** [comment]
Yes, it is! Since typefaces scale differently from HTML elements (which are mostly Cartesian rectangles), I intend to separate the track for scaling typography from the track of scaling UI elements and introduce a unit for that. We can then replace `--bu ` with the appropriate viewport unit depending on the outcome.

**Comment by marvindanig** [comment]
I finished a few tests using `vmin` successfully. While it does not remove the need to use custom property `--bu` on Toucan, it does remove the need to calculate `vmin` per orientation of the viewport. Will update the repos and include this change on our blog posts/documentation. 

Thanks for the great suggestion!
